recall: 
  _target_: torchmetrics.classification.MulticlassRecall
  num_classes: ${max_len} # Maximum DoAs to estimate
  average: "weighted" # all classes are weighted
  zero_division: 1

recall_unweighted: 
  _target_: torchmetrics.classification.MulticlassRecall
  num_classes: ${max_len} # Maximum DoAs to estimate
  average: 'macro' # all classes are treated equally
  zero_division: 1