_target_: hungarian_net.lightning_datamodules.hungarian_datamodule.HungarianDataModule
# _partial_: true
train_filename: ${train_filename}
test_filename: ${test_filename}
max_len: ${max_len}
batch_size: ${batch_size}
num_workers: ${num_workers}
    