### Top-level config file for run.py

# Top-level variables available in all config files
description: "${hydra:runtime.choices.lightning_datamodule}"
max_len: 2 # Maximum DoAs to estimate
num_workers: 4
batch_size: 256
nb_epochs: -1 # testing 
checkpoint_path: "${hydra:runtime.cwd}/checkpoints/20241206/hnet_model_DOA2_6300-4000-1500_epoch=29.ckpt"
train_filename: null
test_filename: "${hydra:runtime.cwd}/data/reference/hung_data_test"
sample_range_trained_on: "6300-4000-1500"
sample_range_tested_on: "3000-5000-15000"

# Hydra configuration
version_base: "1.3"
hydra:
  job:
    chdir: True # change working directory to the job directory
  run:
    dir: "outputs/run/${hydra:runtime.choices.lightning_datamodule}/hnet/${now:%Y-%m-%d_%H-%M-%S}"

# Composing configs
defaults:
  - lightning_datamodule: hungarian_data
  - lightning_module: hnet_gru
  - trainer: ddp
  - callbacks: # Dict of callbacks
      - rich_model_summary
  - logging: test_tensorboard
  - metrics: f1
  - optimizer: adam
  - _self_ # priority is given to run.yaml for overrides