log_every_n_steps: 100

logger:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "${hydra:runtime.cwd}/tb_logs/${now:%y%m%d}/"
  name: 'hnet_model/tested_on_${sample_range_tested_on}/trained_on_${sample_range_trained_on}/standard_resolution'
  version: "hnet_model_DOA${max_len}"
  log_graph: False
  default_hp_metric: False